name: Build everytime push or merge

on:
  push:
    branches:
      - '**'        # matches every branch

defaults:
  run:
    shell: bash

permissions: write-all

jobs:
  build:
    strategy:
      matrix:
        environment: [dev]
    name: "build"
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 20.9.0
        uses: actions/setup-node@v2
        with:
          node-version: 20.9.0

      - name: Run test
        run: |
          npm install

      - name: Jest report
        uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        id: coverage
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-script: "npm run test:full-coverage"
          threshold: 90
          annotations: none
          base-coverage-file: coverage/coverage-final.json

      - name: Build app
        run: |
          npm run build:dev
