name: Build everytime push or merge

on:
  push:
    branches:
      - '**'        # matches every branch

defaults:
  run:
    shell: bash

permissions: write-all

jobs:
  build:
    strategy:
      matrix:
        environment: [uat]
    name: "build"
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Use Node.js 20.9.0
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 20.9.0

      # - name: Build app
      #   run: |
      #     npm install
      #     npm run build
##
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy app version = v1.0.0
        run: |
          aws s3api get-object --bucket ${{ vars.BUCKET_NAME_ARTIFACTS }} --key v1.0.0.zip ./v1.0.0.zip
          unzip v1.0.0.zip
          aws s3 cp build s3://${{ vars.BUCKET_NAME_FRONTEND }}/ --recursive
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
 