name: Build everytime push or merge

on:
  push:
    branches:
      - '**'        # matches every branch

defaults:
  run:
    shell: bash

permissions: write-all

jobs:
  build:
    strategy:
      matrix:
        environment: [dev]
    name: "build"
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 20.9.0
        uses: actions/setup-node@v2
        with:
          node-version: 20.9.0

      - name: Run test
        run: |
          npm install
          npm run test:full-coverage

      - name: JEST Report
        uses: RedaktionsNetzwerk-Deutschland/action-jest-reporter@v1.0.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          json-glob: coverage/coverage-final.json
  
      - name: Build app
        run: |
          npm run build:dev
